# This file is required for the patch-validator to work and may contain advanced configuration options
# For more information, visit https://github.com/szapp/patch-validator/#configuration

prefix:
ignore-declaration:
ignore-resource:
